schema: src/schema/**/*.graphql
extensions:
  codegen:
    overwrite: true
    generates:
      src/generated/resolverTypes.ts:
        config:
          mappers:
            User: src/database/models/User#User
          # mapperTypeSuffix: Model
          contextType: src/context#Context
        plugins:
          - add:
              content: '/* eslint-disable */'
          - 'typescript'
          - 'typescript-resolvers'
