schema: src/schema/**/*.graphql
extensions:
  codegen:
    overwrite: true
    generates:
      ./src/generated/resolverTypes.ts:
        config:
          mappers:
        plugins:
          - 'typescript'
          - 'typescript-resolvers'
