schema: src/schema/**/*.graphql
extensions:
  codegen:
    overwrite: true
    generates:
      src/types/index.ts:
        config:
          maybeValue: T | undefined
          scalars:
            DateTime: Date
          mappers:
            User: src/database/models/User#UserModel
            UserMetadata: src/database/models/UserMetadata#UserMetadataModel
            Device: src/database/models/Device#DeviceModel
            DeviceMetadata: src/database/models/DeviceMetadata#DeviceMetadataModel
          contextType: src/context#Context
        plugins:
          - add:
              content: '/* eslint-disable */'
          - 'typescript'
          - 'typescript-resolvers'
