schema: src/schema/**/*.graphql
extensions:
  codegen:
    overwrite: true
    generates:
      src/types/index.ts:
        config:
          mappers:
            User: src/database/models/User#User
            Metadata: src/database/models/UserMetadata#UserMetadata
          mapperTypeSuffix: Model
          contextType: src/context#Context
        plugins:
          - add:
              content: '/* eslint-disable */'
          - 'typescript'
          - 'typescript-resolvers'
