schema: src/schema/**/*.graphql
extensions:
  codegen:
    overwrite: true
    generates:
      src/types/index.ts:
        config:
          scalars:
            DateTime: Date
          contextType: src/context#Context
          mappers:
            User: src/database/models/User#UserModel
            Device: src/database/models/Device#DeviceModel
          maybeValue: T | undefined
        plugins:
          - add:
              content: '/* eslint-disable */'
          - 'typescript'
          - 'typescript-resolvers'

      client/types/index.tsx:
        documents: 'client/apollo/*.tsx'
        overwrite: true
        config:
          withHooks: true
        plugins:
          - add:
              content: '/* eslint-disable */'
          - 'typescript'
          - 'typescript-operations'
          - 'typescript-react-apollo'
