---
#-------------------------------------------------------------------------------------------------------------
# Here we define our continuous integration compose file,
# this will act as config for our continuous integration environment.
#-------------------------------------------------------------------------------------------------------------

version: "3"
services:
  application:
    # Override default environment variables
    # because continuous integration environment can't
    # access our env file.

    environment:
      - DATABASE_HOST
      - DATABASE_CLIENT
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_NAME
      - CI
