import * as Knex from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('country').del();

  await knex('country').insert([
    { code: 'AF', longName: 'Afghanistan' },
    { code: 'AX', longName: 'Åland Islands' },
    { code: 'AL', longName: 'Albania' },
    { code: 'DZ', longName: 'Algeria' },
    { code: 'AS', longName: 'American Samoa' },
    { code: 'AD', longName: 'Andorra' },
    { code: 'AO', longName: 'Angola' },
    { code: 'AI', longName: 'Anguilla' },
    { code: 'AQ', longName: 'Antarctica' },
    { code: 'AG', longName: 'Antigua & Barbuda' },
    { code: 'AR', longName: 'Argentina' },
    { code: 'AM', longName: 'Armenia' },
    { code: 'AW', longName: 'Aruba' },
    { code: 'AU', longName: 'Australia' },
    { code: 'AT', longName: 'Austria' },
    { code: 'AZ', longName: 'Azerbaijan' },
    { code: 'BS', longName: 'Bahamas' },
    { code: 'BH', longName: 'Bahrain' },
    { code: 'BD', longName: 'Bangladesh' },
    { code: 'BB', longName: 'Barbados' },
    { code: 'BY', longName: 'Belarus' },
    { code: 'BE', longName: 'Belgium' },
    { code: 'BZ', longName: 'Belize' },
    { code: 'BJ', longName: 'Benin' },
    { code: 'BM', longName: 'Bermuda' },
    { code: 'BT', longName: 'Bhutan' },
    { code: 'BO', longName: 'Bolivia' },
    { code: 'BA', longName: 'Bosnia & Herzegovina' },
    { code: 'BW', longName: 'Botswana' },
    { code: 'BV', longName: 'Bouvet Island' },
    { code: 'BR', longName: 'Brazil' },
    { code: 'IO', longName: 'British Indian Ocean Territory' },
    { code: 'VG', longName: 'British Virgin Islands' },
    { code: 'BN', longName: 'Brunei' },
    { code: 'BG', longName: 'Bulgaria' },
    { code: 'BF', longName: 'Burkina Faso' },
    { code: 'BI', longName: 'Burundi' },
    { code: 'KH', longName: 'Cambodia' },
    { code: 'CM', longName: 'Cameroon' },
    { code: 'CA', longName: 'Canada' },
    { code: 'CV', longName: 'Cape Verde' },
    { code: 'BQ', longName: 'Caribbean Netherlands' },
    { code: 'KY', longName: 'Cayman Islands' },
    { code: 'CF', longName: 'Central African Republic' },
    { code: 'TD', longName: 'Chad' },
    { code: 'CL', longName: 'Chile' },
    { code: 'CN', longName: 'China' },
    { code: 'CX', longName: 'Christmas Island' },
    { code: 'CC', longName: 'Cocos (Keeling) Islands' },
    { code: 'CO', longName: 'Colombia' },
    { code: 'KM', longName: 'Comoros' },
    { code: 'CG', longName: 'Congo - Brazzaville' },
    { code: 'CD', longName: 'Congo - Kinshasa' },
    { code: 'CK', longName: 'Cook Islands' },
    { code: 'CR', longName: 'Costa Rica' },
    { code: 'CI', longName: 'Côte d’Ivoire' },
    { code: 'HR', longName: 'Croatia' },
    { code: 'CU', longName: 'Cuba' },
    { code: 'CW', longName: 'Curaçao' },
    { code: 'CY', longName: 'Cyprus' },
    { code: 'CZ', longName: 'Czechia' },
    { code: 'DK', longName: 'Denmark' },
    { code: 'DJ', longName: 'Djibouti' },
    { code: 'DM', longName: 'Dominica' },
    { code: 'DO', longName: 'Dominican Republic' },
    { code: 'EC', longName: 'Ecuador' },
    { code: 'EG', longName: 'Egypt' },
    { code: 'SV', longName: 'El Salvador' },
    { code: 'GQ', longName: 'Equatorial Guinea' },
    { code: 'ER', longName: 'Eritrea' },
    { code: 'EE', longName: 'Estonia' },
    { code: 'SZ', longName: 'Eswatini' },
    { code: 'ET', longName: 'Ethiopia' },
    { code: 'FK', longName: 'Falkland Islands' },
    { code: 'FO', longName: 'Faroe Islands' },
    { code: 'FJ', longName: 'Fiji' },
    { code: 'FI', longName: 'Finland' },
    { code: 'FR', longName: 'France' },
    { code: 'GF', longName: 'French Guiana' },
    { code: 'PF', longName: 'French Polynesia' },
    { code: 'TF', longName: 'French Southern Territories' },
    { code: 'GA', longName: 'Gabon' },
    { code: 'GM', longName: 'Gambia' },
    { code: 'GE', longName: 'Georgia' },
    { code: 'DE', longName: 'Germany' },
    { code: 'GH', longName: 'Ghana' },
    { code: 'GI', longName: 'Gibraltar' },
    { code: 'GR', longName: 'Greece' },
    { code: 'GL', longName: 'Greenland' },
    { code: 'GD', longName: 'Grenada' },
    { code: 'GP', longName: 'Guadeloupe' },
    { code: 'GU', longName: 'Guam' },
    { code: 'GT', longName: 'Guatemala' },
    { code: 'GG', longName: 'Guernsey' },
    { code: 'GN', longName: 'Guinea' },
    { code: 'GW', longName: 'Guinea-Bissau' },
    { code: 'GY', longName: 'Guyana' },
    { code: 'HT', longName: 'Haiti' },
    { code: 'HM', longName: 'Heard & McDonald Islands' },
    { code: 'HN', longName: 'Honduras' },
    { code: 'HK', longName: 'Hong Kong SAR China' },
    { code: 'HU', longName: 'Hungary' },
    { code: 'IS', longName: 'Iceland' },
    { code: 'IN', longName: 'India' },
    { code: 'ID', longName: 'Indonesia' },
    { code: 'IR', longName: 'Iran' },
    { code: 'IQ', longName: 'Iraq' },
    { code: 'IE', longName: 'Ireland' },
    { code: 'IM', longName: 'Isle of Man' },
    { code: 'IL', longName: 'Israel' },
    { code: 'IT', longName: 'Italy' },
    { code: 'JM', longName: 'Jamaica' },
    { code: 'JP', longName: 'Japan' },
    { code: 'JE', longName: 'Jersey' },
    { code: 'JO', longName: 'Jordan' },
    { code: 'KZ', longName: 'Kazakhstan' },
    { code: 'KE', longName: 'Kenya' },
    { code: 'KI', longName: 'Kiribati' },
    { code: 'KW', longName: 'Kuwait' },
    { code: 'KG', longName: 'Kyrgyzstan' },
    { code: 'LA', longName: 'Laos' },
    { code: 'LV', longName: 'Latvia' },
    { code: 'LB', longName: 'Lebanon' },
    { code: 'LS', longName: 'Lesotho' },
    { code: 'LR', longName: 'Liberia' },
    { code: 'LY', longName: 'Libya' },
    { code: 'LI', longName: 'Liechtenstein' },
    { code: 'LT', longName: 'Lithuania' },
    { code: 'LU', longName: 'Luxembourg' },
    { code: 'MO', longName: 'Macao SAR China' },
    { code: 'MG', longName: 'Madagascar' },
    { code: 'MW', longName: 'Malawi' },
    { code: 'MY', longName: 'Malaysia' },
    { code: 'MV', longName: 'Maldives' },
    { code: 'ML', longName: 'Mali' },
    { code: 'MT', longName: 'Malta' },
    { code: 'MH', longName: 'Marshall Islands' },
    { code: 'MQ', longName: 'Martinique' },
    { code: 'MR', longName: 'Mauritania' },
    { code: 'MU', longName: 'Mauritius' },
    { code: 'YT', longName: 'Mayotte' },
    { code: 'MX', longName: 'Mexico' },
    { code: 'FM', longName: 'Micronesia' },
    { code: 'MD', longName: 'Moldova' },
    { code: 'MC', longName: 'Monaco' },
    { code: 'MN', longName: 'Mongolia' },
    { code: 'ME', longName: 'Montenegro' },
    { code: 'MS', longName: 'Montserrat' },
    { code: 'MA', longName: 'Morocco' },
    { code: 'MZ', longName: 'Mozambique' },
    { code: 'MM', longName: 'Myanmar (Burma)' },
    { code: 'NA', longName: 'Namibia' },
    { code: 'NR', longName: 'Nauru' },
    { code: 'NP', longName: 'Nepal' },
    { code: 'NL', longName: 'Netherlands' },
    { code: 'NC', longName: 'New Caledonia' },
    { code: 'NZ', longName: 'New Zealand' },
    { code: 'NI', longName: 'Nicaragua' },
    { code: 'NE', longName: 'Niger' },
    { code: 'NG', longName: 'Nigeria' },
    { code: 'NU', longName: 'Niue' },
    { code: 'NF', longName: 'Norfolk Island' },
    { code: 'KP', longName: 'North Korea' },
    { code: 'MK', longName: 'North Macedonia' },
    { code: 'MP', longName: 'Northern Mariana Islands' },
    { code: 'NO', longName: 'Norway' },
    { code: 'OM', longName: 'Oman' },
    { code: 'PK', longName: 'Pakistan' },
    { code: 'PW', longName: 'Palau' },
    { code: 'PS', longName: 'Palestinian Territories' },
    { code: 'PA', longName: 'Panama' },
    { code: 'PG', longName: 'Papua New Guinea' },
    { code: 'PY', longName: 'Paraguay' },
    { code: 'PE', longName: 'Peru' },
    { code: 'PH', longName: 'Philippines' },
    { code: 'PN', longName: 'Pitcairn Islands' },
    { code: 'PL', longName: 'Poland' },
    { code: 'PT', longName: 'Portugal' },
    { code: 'PR', longName: 'Puerto Rico' },
    { code: 'QA', longName: 'Qatar' },
    { code: 'RE', longName: 'Réunion' },
    { code: 'RO', longName: 'Romania' },
    { code: 'RU', longName: 'Russia' },
    { code: 'RW', longName: 'Rwanda' },
    { code: 'WS', longName: 'Samoa' },
    { code: 'SM', longName: 'San Marino' },
    { code: 'ST', longName: 'São Tomé & Príncipe' },
    { code: 'SA', longName: 'Saudi Arabia' },
    { code: 'SN', longName: 'Senegal' },
    { code: 'RS', longName: 'Serbia' },
    { code: 'SC', longName: 'Seychelles' },
    { code: 'SL', longName: 'Sierra Leone' },
    { code: 'SG', longName: 'Singapore' },
    { code: 'SX', longName: 'Sint Maarten' },
    { code: 'SK', longName: 'Slovakia' },
    { code: 'SI', longName: 'Slovenia' },
    { code: 'SB', longName: 'Solomon Islands' },
    { code: 'SO', longName: 'Somalia' },
    { code: 'ZA', longName: 'South Africa' },
    { code: 'GS', longName: 'South Georgia & South Sandwich Islands' },
    { code: 'KR', longName: 'South Korea' },
    { code: 'SS', longName: 'South Sudan' },
    { code: 'ES', longName: 'Spain' },
    { code: 'LK', longName: 'Sri Lanka' },
    { code: 'BL', longName: 'St. Barthélemy' },
    { code: 'SH', longName: 'St. Helena' },
    { code: 'KN', longName: 'St. Kitts & Nevis' },
    { code: 'LC', longName: 'St. Lucia' },
    { code: 'MF', longName: 'St. Martin' },
    { code: 'PM', longName: 'St. Pierre & Miquelon' },
    { code: 'VC', longName: 'St. Vincent & Grenadines' },
    { code: 'SD', longName: 'Sudan' },
    { code: 'SR', longName: 'SurilongName' },
    { code: 'SJ', longName: 'Svalbard & Jan Mayen' },
    { code: 'SE', longName: 'Sweden' },
    { code: 'CH', longName: 'Switzerland' },
    { code: 'SY', longName: 'Syria' },
    { code: 'TW', longName: 'Taiwan' },
    { code: 'TJ', longName: 'Tajikistan' },
    { code: 'TZ', longName: 'Tanzania' },
    { code: 'TH', longName: 'Thailand' },
    { code: 'TL', longName: 'Timor-Leste' },
    { code: 'TG', longName: 'Togo' },
    { code: 'TK', longName: 'Tokelau' },
    { code: 'TO', longName: 'Tonga' },
    { code: 'TT', longName: 'Trincodead & Tobago' },
    { code: 'TN', longName: 'Tunisia' },
    { code: 'TR', longName: 'Turkey' },
    { code: 'TM', longName: 'Turkmenistan' },
    { code: 'TC', longName: 'Turks & Caicos Islands' },
    { code: 'TV', longName: 'Tuvalu' },
    { code: 'UM', longName: 'U.S. Outlying Islands' },
    { code: 'VI', longName: 'U.S. Virgin Islands' },
    { code: 'UG', longName: 'Uganda' },
    { code: 'UA', longName: 'Ukraine' },
    { code: 'AE', longName: 'United Arab Emirates' },
    { code: 'GB', longName: 'United Kingdom' },
    { code: 'US', longName: 'United States' },
    { code: 'UY', longName: 'Uruguay' },
    { code: 'UZ', longName: 'Uzbekistan' },
    { code: 'VU', longName: 'Vanuatu' },
    { code: 'VA', longName: 'Vatican City' },
    { code: 'VE', longName: 'Venezuela' },
    { code: 'VN', longName: 'Vietnam' },
    { code: 'WF', longName: 'Wallis & Futuna' },
    { code: 'EH', longName: 'Western Sahara' },
    { code: 'YE', longName: 'Yemen' },
    { code: 'ZM', longName: 'Zambia' },
    { code: 'ZW', longName: 'Zimbabwe' },
  ]);
}
