import * as Knex from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('country').del();

  await knex('country').insert([
    { code: 'AF', long_name: 'Afghanistan' },
    { code: 'AX', long_name: 'Åland Islands' },
    { code: 'AL', long_name: 'Albania' },
    { code: 'DZ', long_name: 'Algeria' },
    { code: 'AS', long_name: 'American Samoa' },
    { code: 'AD', long_name: 'Andorra' },
    { code: 'AO', long_name: 'Angola' },
    { code: 'AI', long_name: 'Anguilla' },
    { code: 'AQ', long_name: 'Antarctica' },
    { code: 'AG', long_name: 'Antigua & Barbuda' },
    { code: 'AR', long_name: 'Argentina' },
    { code: 'AM', long_name: 'Armenia' },
    { code: 'AW', long_name: 'Aruba' },
    { code: 'AU', long_name: 'Australia' },
    { code: 'AT', long_name: 'Austria' },
    { code: 'AZ', long_name: 'Azerbaijan' },
    { code: 'BS', long_name: 'Bahamas' },
    { code: 'BH', long_name: 'Bahrain' },
    { code: 'BD', long_name: 'Bangladesh' },
    { code: 'BB', long_name: 'Barbados' },
    { code: 'BY', long_name: 'Belarus' },
    { code: 'BE', long_name: 'Belgium' },
    { code: 'BZ', long_name: 'Belize' },
    { code: 'BJ', long_name: 'Benin' },
    { code: 'BM', long_name: 'Bermuda' },
    { code: 'BT', long_name: 'Bhutan' },
    { code: 'BO', long_name: 'Bolivia' },
    { code: 'BA', long_name: 'Bosnia & Herzegovina' },
    { code: 'BW', long_name: 'Botswana' },
    { code: 'BV', long_name: 'Bouvet Island' },
    { code: 'BR', long_name: 'Brazil' },
    { code: 'IO', long_name: 'British Indian Ocean Territory' },
    { code: 'VG', long_name: 'British Virgin Islands' },
    { code: 'BN', long_name: 'Brunei' },
    { code: 'BG', long_name: 'Bulgaria' },
    { code: 'BF', long_name: 'Burkina Faso' },
    { code: 'BI', long_name: 'Burundi' },
    { code: 'KH', long_name: 'Cambodia' },
    { code: 'CM', long_name: 'Cameroon' },
    { code: 'CA', long_name: 'Canada' },
    { code: 'CV', long_name: 'Cape Verde' },
    { code: 'BQ', long_name: 'Caribbean Netherlands' },
    { code: 'KY', long_name: 'Cayman Islands' },
    { code: 'CF', long_name: 'Central African Republic' },
    { code: 'TD', long_name: 'Chad' },
    { code: 'CL', long_name: 'Chile' },
    { code: 'CN', long_name: 'China' },
    { code: 'CX', long_name: 'Christmas Island' },
    { code: 'CC', long_name: 'Cocos (Keeling) Islands' },
    { code: 'CO', long_name: 'Colombia' },
    { code: 'KM', long_name: 'Comoros' },
    { code: 'CG', long_name: 'Congo - Brazzaville' },
    { code: 'CD', long_name: 'Congo - Kinshasa' },
    { code: 'CK', long_name: 'Cook Islands' },
    { code: 'CR', long_name: 'Costa Rica' },
    { code: 'CI', long_name: 'Côte d’Ivoire' },
    { code: 'HR', long_name: 'Croatia' },
    { code: 'CU', long_name: 'Cuba' },
    { code: 'CW', long_name: 'Curaçao' },
    { code: 'CY', long_name: 'Cyprus' },
    { code: 'CZ', long_name: 'Czechia' },
    { code: 'DK', long_name: 'Denmark' },
    { code: 'DJ', long_name: 'Djibouti' },
    { code: 'DM', long_name: 'Dominica' },
    { code: 'DO', long_name: 'Dominican Republic' },
    { code: 'EC', long_name: 'Ecuador' },
    { code: 'EG', long_name: 'Egypt' },
    { code: 'SV', long_name: 'El Salvador' },
    { code: 'GQ', long_name: 'Equatorial Guinea' },
    { code: 'ER', long_name: 'Eritrea' },
    { code: 'EE', long_name: 'Estonia' },
    { code: 'SZ', long_name: 'Eswatini' },
    { code: 'ET', long_name: 'Ethiopia' },
    { code: 'FK', long_name: 'Falkland Islands' },
    { code: 'FO', long_name: 'Faroe Islands' },
    { code: 'FJ', long_name: 'Fiji' },
    { code: 'FI', long_name: 'Finland' },
    { code: 'FR', long_name: 'France' },
    { code: 'GF', long_name: 'French Guiana' },
    { code: 'PF', long_name: 'French Polynesia' },
    { code: 'TF', long_name: 'French Southern Territories' },
    { code: 'GA', long_name: 'Gabon' },
    { code: 'GM', long_name: 'Gambia' },
    { code: 'GE', long_name: 'Georgia' },
    { code: 'DE', long_name: 'Germany' },
    { code: 'GH', long_name: 'Ghana' },
    { code: 'GI', long_name: 'Gibraltar' },
    { code: 'GR', long_name: 'Greece' },
    { code: 'GL', long_name: 'Greenland' },
    { code: 'GD', long_name: 'Grenada' },
    { code: 'GP', long_name: 'Guadeloupe' },
    { code: 'GU', long_name: 'Guam' },
    { code: 'GT', long_name: 'Guatemala' },
    { code: 'GG', long_name: 'Guernsey' },
    { code: 'GN', long_name: 'Guinea' },
    { code: 'GW', long_name: 'Guinea-Bissau' },
    { code: 'GY', long_name: 'Guyana' },
    { code: 'HT', long_name: 'Haiti' },
    { code: 'HM', long_name: 'Heard & McDonald Islands' },
    { code: 'HN', long_name: 'Honduras' },
    { code: 'HK', long_name: 'Hong Kong SAR China' },
    { code: 'HU', long_name: 'Hungary' },
    { code: 'IS', long_name: 'Iceland' },
    { code: 'IN', long_name: 'India' },
    { code: 'ID', long_name: 'Indonesia' },
    { code: 'IR', long_name: 'Iran' },
    { code: 'IQ', long_name: 'Iraq' },
    { code: 'IE', long_name: 'Ireland' },
    { code: 'IM', long_name: 'Isle of Man' },
    { code: 'IL', long_name: 'Israel' },
    { code: 'IT', long_name: 'Italy' },
    { code: 'JM', long_name: 'Jamaica' },
    { code: 'JP', long_name: 'Japan' },
    { code: 'JE', long_name: 'Jersey' },
    { code: 'JO', long_name: 'Jordan' },
    { code: 'KZ', long_name: 'Kazakhstan' },
    { code: 'KE', long_name: 'Kenya' },
    { code: 'KI', long_name: 'Kiribati' },
    { code: 'KW', long_name: 'Kuwait' },
    { code: 'KG', long_name: 'Kyrgyzstan' },
    { code: 'LA', long_name: 'Laos' },
    { code: 'LV', long_name: 'Latvia' },
    { code: 'LB', long_name: 'Lebanon' },
    { code: 'LS', long_name: 'Lesotho' },
    { code: 'LR', long_name: 'Liberia' },
    { code: 'LY', long_name: 'Libya' },
    { code: 'LI', long_name: 'Liechtenstein' },
    { code: 'LT', long_name: 'Lithuania' },
    { code: 'LU', long_name: 'Luxembourg' },
    { code: 'MO', long_name: 'Macao SAR China' },
    { code: 'MG', long_name: 'Madagascar' },
    { code: 'MW', long_name: 'Malawi' },
    { code: 'MY', long_name: 'Malaysia' },
    { code: 'MV', long_name: 'Maldives' },
    { code: 'ML', long_name: 'Mali' },
    { code: 'MT', long_name: 'Malta' },
    { code: 'MH', long_name: 'Marshall Islands' },
    { code: 'MQ', long_name: 'Martinique' },
    { code: 'MR', long_name: 'Mauritania' },
    { code: 'MU', long_name: 'Mauritius' },
    { code: 'YT', long_name: 'Mayotte' },
    { code: 'MX', long_name: 'Mexico' },
    { code: 'FM', long_name: 'Micronesia' },
    { code: 'MD', long_name: 'Moldova' },
    { code: 'MC', long_name: 'Monaco' },
    { code: 'MN', long_name: 'Mongolia' },
    { code: 'ME', long_name: 'Montenegro' },
    { code: 'MS', long_name: 'Montserrat' },
    { code: 'MA', long_name: 'Morocco' },
    { code: 'MZ', long_name: 'Mozambique' },
    { code: 'MM', long_name: 'Myanmar (Burma)' },
    { code: 'NA', long_name: 'Namibia' },
    { code: 'NR', long_name: 'Nauru' },
    { code: 'NP', long_name: 'Nepal' },
    { code: 'NL', long_name: 'Netherlands' },
    { code: 'NC', long_name: 'New Caledonia' },
    { code: 'NZ', long_name: 'New Zealand' },
    { code: 'NI', long_name: 'Nicaragua' },
    { code: 'NE', long_name: 'Niger' },
    { code: 'NG', long_name: 'Nigeria' },
    { code: 'NU', long_name: 'Niue' },
    { code: 'NF', long_name: 'Norfolk Island' },
    { code: 'KP', long_name: 'North Korea' },
    { code: 'MK', long_name: 'North Macedonia' },
    { code: 'MP', long_name: 'Northern Mariana Islands' },
    { code: 'NO', long_name: 'Norway' },
    { code: 'OM', long_name: 'Oman' },
    { code: 'PK', long_name: 'Pakistan' },
    { code: 'PW', long_name: 'Palau' },
    { code: 'PS', long_name: 'Palestinian Territories' },
    { code: 'PA', long_name: 'Panama' },
    { code: 'PG', long_name: 'Papua New Guinea' },
    { code: 'PY', long_name: 'Paraguay' },
    { code: 'PE', long_name: 'Peru' },
    { code: 'PH', long_name: 'Philippines' },
    { code: 'PN', long_name: 'Pitcairn Islands' },
    { code: 'PL', long_name: 'Poland' },
    { code: 'PT', long_name: 'Portugal' },
    { code: 'PR', long_name: 'Puerto Rico' },
    { code: 'QA', long_name: 'Qatar' },
    { code: 'RE', long_name: 'Réunion' },
    { code: 'RO', long_name: 'Romania' },
    { code: 'RU', long_name: 'Russia' },
    { code: 'RW', long_name: 'Rwanda' },
    { code: 'WS', long_name: 'Samoa' },
    { code: 'SM', long_name: 'San Marino' },
    { code: 'ST', long_name: 'São Tomé & Príncipe' },
    { code: 'SA', long_name: 'Saudi Arabia' },
    { code: 'SN', long_name: 'Senegal' },
    { code: 'RS', long_name: 'Serbia' },
    { code: 'SC', long_name: 'Seychelles' },
    { code: 'SL', long_name: 'Sierra Leone' },
    { code: 'SG', long_name: 'Singapore' },
    { code: 'SX', long_name: 'Sint Maarten' },
    { code: 'SK', long_name: 'Slovakia' },
    { code: 'SI', long_name: 'Slovenia' },
    { code: 'SB', long_name: 'Solomon Islands' },
    { code: 'SO', long_name: 'Somalia' },
    { code: 'ZA', long_name: 'South Africa' },
    { code: 'GS', long_name: 'South Georgia & South Sandwich Islands' },
    { code: 'KR', long_name: 'South Korea' },
    { code: 'SS', long_name: 'South Sudan' },
    { code: 'ES', long_name: 'Spain' },
    { code: 'LK', long_name: 'Sri Lanka' },
    { code: 'BL', long_name: 'St. Barthélemy' },
    { code: 'SH', long_name: 'St. Helena' },
    { code: 'KN', long_name: 'St. Kitts & Nevis' },
    { code: 'LC', long_name: 'St. Lucia' },
    { code: 'MF', long_name: 'St. Martin' },
    { code: 'PM', long_name: 'St. Pierre & Miquelon' },
    { code: 'VC', long_name: 'St. Vincent & Grenadines' },
    { code: 'SD', long_name: 'Sudan' },
    { code: 'SR', long_name: 'Surilong_name' },
    { code: 'SJ', long_name: 'Svalbard & Jan Mayen' },
    { code: 'SE', long_name: 'Sweden' },
    { code: 'CH', long_name: 'Switzerland' },
    { code: 'SY', long_name: 'Syria' },
    { code: 'TW', long_name: 'Taiwan' },
    { code: 'TJ', long_name: 'Tajikistan' },
    { code: 'TZ', long_name: 'Tanzania' },
    { code: 'TH', long_name: 'Thailand' },
    { code: 'TL', long_name: 'Timor-Leste' },
    { code: 'TG', long_name: 'Togo' },
    { code: 'TK', long_name: 'Tokelau' },
    { code: 'TO', long_name: 'Tonga' },
    { code: 'TT', long_name: 'Trincodead & Tobago' },
    { code: 'TN', long_name: 'Tunisia' },
    { code: 'TR', long_name: 'Turkey' },
    { code: 'TM', long_name: 'Turkmenistan' },
    { code: 'TC', long_name: 'Turks & Caicos Islands' },
    { code: 'TV', long_name: 'Tuvalu' },
    { code: 'UM', long_name: 'U.S. Outlying Islands' },
    { code: 'VI', long_name: 'U.S. Virgin Islands' },
    { code: 'UG', long_name: 'Uganda' },
    { code: 'UA', long_name: 'Ukraine' },
    { code: 'AE', long_name: 'United Arab Emirates' },
    { code: 'GB', long_name: 'United Kingdom' },
    { code: 'US', long_name: 'United States' },
    { code: 'UY', long_name: 'Uruguay' },
    { code: 'UZ', long_name: 'Uzbekistan' },
    { code: 'VU', long_name: 'Vanuatu' },
    { code: 'VA', long_name: 'Vatican City' },
    { code: 'VE', long_name: 'Venezuela' },
    { code: 'VN', long_name: 'Vietnam' },
    { code: 'WF', long_name: 'Wallis & Futuna' },
    { code: 'EH', long_name: 'Western Sahara' },
    { code: 'YE', long_name: 'Yemen' },
    { code: 'ZM', long_name: 'Zambia' },
    { code: 'ZW', long_name: 'Zimbabwe' },
  ]);
}
